name: intercom
description: Flutter Intercom integration
version: 0.0.2
author: Maido Käära <maido@getchange.com>
homepage: https://github.com/ChangeFinance/intercom_flutter

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^2.2.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.getchange.intercom
    pluginClass: IntercomPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.5.0 <2.0.0"
