name: intercom_example
description: Demonstrates how to use the intercom_flutter plugin.
publish_to: none

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  intercom_flutter:
    path: ../

dependency_overrides:
  intercom_flutter:
    path: ../
  intercom_flutter_platform_interface:
    path: ../../intercom_flutter_platform_interface
  intercom_flutter_web:
    path: ../../intercom_flutter_web

flutter:
  uses-material-design: true

environment:
  sdk: '>=3.0.0 <4.0.0'
