version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    environment:
      CODECOV_TOKEN: a2c3e067-68e0-4d4f-a302-f68376c30232
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter analyze
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: coverage/lcov.info
