name: intercom_flutter
description: Flutter plugin for Intercom integration. Provides in-app messaging
  and help-center Intercom services
version: 8.0.7
homepage: https://github.com/v3rm0n/intercom_flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intercom_flutter_platform_interface: ^2.0.0
  intercom_flutter_web: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  collection: ^1.17.2

flutter:
  plugin:
    platforms:
      android:
        package: io.maido.intercom
        pluginClass: IntercomFlutterPlugin
      ios:
        pluginClass: IntercomFlutterPlugin
      web:
        default_package: intercom_flutter_web

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
