name: intercom_flutter_web
description: Web platform implementation of intercom_flutter
version: 1.0.0
homepage: https://github.com/v3rm0n/intercom_flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: IntercomFlutterWeb
        fileName: intercom_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intercom_flutter_platform_interface: ^2.0.0
  uuid: ^3.0.7 # to get the random uuid for loginUnidentifiedUser in web

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"