name: regular_integration_tests
publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  intercom_flutter_web:
    path: ../
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  crypto: ^3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.26.0-0" # For integration_test from sdk
