name: intercom_flutter_platform_interface
description: A common platform interface for the intercom_flutter plugin.
version: 2.0.2
homepage: https://github.com/v3rm0n/intercom_flutter

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

environment:
  sdk: '>=3.0.0 <4.0.0'
